version: '3'
services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile.tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps

  express:
    build:
      context: .
      dockerfile: Dockerfile.express
    ports:
      - "3000:3000"
    volumes:
      - ./express:/usr/src/app