FROM tomcat:9-jdk11-openjdk-slim

# Remove default Tomcat applications
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy your JSP files to the webapps directory
COPY ./webapps/ /usr/local/tomcat/webapps/

# Expose the default Tomcat port
EXPOSE 8080

CMD ["catalina.sh", "run"]
