version: '3'
services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile.tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql-data:

networks:
  app_network:
    driver: bridge
