FROM node:20-alpine3.20

WORKDIR /usr/src/app

# Install MySQL client
# RUN apk add --no-cache mysql-client

COPY ./express/package*.json ./

RUN npm install

COPY ./express .
COPY .env .

EXPOSE 3000

CMD ["npm", "start"]
