version: '3'
services:
  web:
    image: tomcat:9-jdk17-openjdk
    restart: always
    container_name: web
    # build:
      # context: ./src
      # dockerfile: Dockerfile.tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/webapps/midoripol.war:/usr/local/tomcat/webapps/ROOT.war

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql-data:

networks:
  app_network:
    driver: bridge
